package:
    name: soma-python
    version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-soma-base
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-soma-base-usrdoc
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-soma-workflow
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-soma-workflow-usrdoc

  run:
    - python >= 3.9
    - populse-db >= 3.0

tests:
  - script: "python -m soma.tests"
    requirements:
      run:
        - pytest
  - script: "python -m soma_workflow.test"
    requirements:
      run:
        - pytest
