package:
    name: cati
    version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }}

requirements:
  run:
    - qualicati
    - cati-longitudinal
    - cati-rsfmri
    - cati-sacha
    - cati-whasa
    - cati-deidentification
    - catidb
    - nuclear-imaging
