package:
    name: capsul
    # version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/src/capsul/pyproject.toml").project.version }}
    version: 3.0.0

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-populse-db
    env BRAINVISA_INSTALL_PREFIX="$PREFIX" make install-populse-db-usrdoc

requirements:
  run:
    - soma-python

tests:
  - script: "python -m populse_db.test"
    requirements:
      run:
        - pytest
