package:
    name: soma-spm
    version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    export BRAINVISA_INSTALL_PREFIX="$PREFIX"
    for component in brainvisa-spm; do
      make install-${component}
      make install-${component}-dev
      make install-${component}-usrdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
    done

requirements:
  build:
    - make

  run:
    - soma
    - anatomist

# tests:
#   - script: "python -m soma.tests"
#     requirements:
#       run:
#         - pytest
#   - script: "python -m soma_workflow.test"
#     requirements:
#       run:
#         - pytest
